### ISSUE TITLE
Mac OSX build error

### ISSUE THREAD

**Issue by S1W** [agurodriguez/brute_force_bip38#1]
When building on OSX Mojave this error appears:

`-- Configuring done
CMake Error at third_party/libwally-core/CMakeLists.txt:41 (add_library):
  Cannot find source file:

    src/secp256k1/src/secp256k1.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at third_party/libwally-core/CMakeLists.txt:5 (add_library):
  Cannot find source file:

    src/aes.c

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

CMake Error at third_party/libwally-core/CMakeLists.txt:41 (add_library):
  No SOURCES given to target: secp256k1

CMake Error at third_party/libwally-core/CMakeLists.txt:5 (add_library):
  No SOURCES given to target: libwally-core
`

**Comment by agurod42** [comment]
Hi @S1W!

I think you haven't cloned the libwally-core submodule. Could you try cloning the repo this way:

```
git clone https://github.com/agurodriguez/brute_force_bip38.git --recursive
```  

and let me know if it works for you?
